server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Redirection des appels API vers le conteneur backend Node.js
    location /api/ {
        proxy_pass http://pktm-backend:3000; # Nom du service dans Docker Compose + port Node.js
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}